# Generated by Django 5.2.5 on 2025-08-10 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos/')),
                ('symbol', models.CharField(max_length=16, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('year_founded', models.IntegerField(help_text='Year the company was founded', validators=[django.core.validators.MaxValueValidator(2025)])),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
